### ISSUE TITLE
unsupported operand type error when loading trained model

### ISSUE THREAD

**Issue by indam23** [bplank/bilstm-aux#12]
When running bilty.py and loading trained model, the following error occurs:
```
python3 src/bilty.py --dynet-mem 5000 --model "models/test1.model" --dev data/da-ud-dev.conllu --pred_layer 1 --dynet-gpus 1 --output predictions/pred1 --save models/test1
[dynet] random seed: 2913040757
[dynet] allocating memory: 5000MB
[dynet] memory allocation done.
loading model from file models/test1.model
Traceback (most recent call last):
  File "src/bilty.py", line 767, in <module>
    main()
  File "src/bilty.py", line 113, in main
    tagger = load(args)
  File "src/bilty.py", line 188, in load
    myparams = pickle.load(open(model_path+".params.pickle", "rb"))
TypeError: unsupported operand type(s) for +: 'Namespace' and 'str'
```
It looks like line 113 in bilty.py ` tagger = load(args)` should be `tagger = load(args.model)` - is this correct?

**Comment by indam23** [comment]
fixed in https://github.com/bplank/bilstm-aux/commit/34d789f41668f40172c34d809093f708960727d9
