### ISSUE TITLE
Bi-LSTM fails because of imcomplete move to Dynet

### ISSUE THREAD

**Issue by bplank** [bplank/bilstm-aux#3]
> Hi Barbara,
> 
> I tried playing with your bi-LSTM tagger. [..]  However, after loading the source files successfully following
> your example, it throws an error:
> Traceback (most recent call last):
>   File "src/bilty.py", line 567, in <module>
>     main()
>   File "src/bilty.py", line 86, in main
>     tagger.fit(args.train, args.iters, args.trainer, dev=args.dev)
>   File "src/bilty.py", line 222, in fit
>     self.predictors, self.char_rnn, self.wembeds, self.cembeds =
> self.build_computation_graph(num_words, num_chars)
>   File "src/bilty.py", line 261, in build_computation_graph
>     wembeds = self.model.add_lookup_parameters("lookup_wembeds", (num_words,
> self.in_dim))
> TypeError: add_lookup_parameters() takes exactly one argument (2 given)

Dynet's library has changed. Although the documentation moved, the source code of the tagger hasn't. Working on it.

**Comment by bplank** [comment]
solution: moved the bilty code to DyNet, add_lookup_parameters take no string/naming option any longer. Updated code and README. now the code should work with DyNet.
